// This is the event table from the scouting doc. Make sure
// it's kept in sync with what processing expects.

type MatchEvent = {
  phase: "pre-match" | "sandstorm" | "teleop" | "post-match",
  description: string
}

export const EventTypes: { [index: string]: MatchEvent } = {
  // Pre-match
  31: { phase: "pre-match", description: "Started position 1" },
  32: { phase: "pre-match", description: "Started position 2" },
  33: { phase: "pre-match", description: "Started position 3" },

  // Sandstorm
  0: { phase: "sandstorm", description: "[SANDSTORM] Crossed starting line" },
  20: { phase: "sandstorm", description: "[SANDSTORM] Grabbed hatch floor" },
  21: { phase: "sandstorm", description: "[SANDSTORM] Grabbed hatch station" },
  40: { phase: "sandstorm", description: "[SANDSTORM] Grabbed cargo floor" },
  41: { phase: "sandstorm", description: "[SANDSTORM] Grabbed cargo station" },
  25: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on front rocket bottom" },
  27: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on front rocket middle" },
  29: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on front rocket top" },
  24: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on back rocket bottom" },
  26: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on back rocket middle" },
  28: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on back rocket top" },
  44: { phase: "sandstorm", description: "[SANDSTORM] Scored cargo on rocket bottom" },
  45: { phase: "sandstorm", description: "[SANDSTORM] Scored cargo on rocket middle" },
  46: { phase: "sandstorm", description: "[SANDSTORM] Scored cargo on rocket top" },
  23: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on ship side" },
  22: { phase: "sandstorm", description: "[SANDSTORM] Scored hatch on ship front" },
  43: { phase: "sandstorm", description: "[SANDSTORM] Scored cargo on ship side" },
  42: { phase: "sandstorm", description: "[SANDSTORM] Scored cargo on ship front" },
  2: { phase: "sandstorm", description: "[SANDSTORM] Dropped hatch" },
  3: { phase: "sandstorm", description: "[SANDSTORM] Dropped cargo" },
  1: { phase: "sandstorm", description: "[SANDSTORM] Entered opponent territory" },
  4: { phase: "sandstorm", description: "[SANDSTORM] Left opponent territory" },

  // Teleop
  120: { phase: "teleop", description: "Grabbed hatch floor" },
  121: { phase: "teleop", description: "Grabbed hatch station" },
  140: { phase: "teleop", description: "Grabbed cargo floor" },
  141: { phase: "teleop", description: "Grabbed cargo station" },
  125: { phase: "teleop", description: "Scored hatch on front rocket bottom" },
  127: { phase: "teleop", description: "Scored hatch on front rocket middle" },
  129: { phase: "teleop", description: "Scored hatch on front rocket top" },
  124: { phase: "teleop", description: "Scored hatch on back rocket bottom" },
  126: { phase: "teleop", description: "Scored hatch on back rocket middle" },
  128: { phase: "teleop", description: "Scored hatch on back rocket top" },
  144: { phase: "teleop", description: "Scored cargo on rocket bottom" },
  145: { phase: "teleop", description: "Scored cargo on rocket middle" },
  146: { phase: "teleop", description: "Scored cargo on rocket top" },
  123: { phase: "teleop", description: "Scored hatch on ship side" },
  122: { phase: "teleop", description: "Scored hatch on ship front" },
  143: { phase: "teleop", description: "Scored cargo on ship side" },
  142: { phase: "teleop", description: "Scored cargo on ship front" },
  5: { phase: "teleop", description: "Disabled" },
  6: { phase: "teleop", description: "Restored" },
  12: { phase: "teleop", description: "Dropped Hatch" },
  13: { phase: "teleop", description: "Dropped cargo" },
  11: { phase: "teleop", description: "Entered opponent territory" },
  14: { phase: "teleop", description: "Left opponent territory" },

  // Post-match
  212: { phase: "post-match", description: "Lifted teammate to 2" },
  213: { phase: "post-match", description: "Lifted teammate to 3" },
  201: { phase: "post-match", description: "Ended match on 1" },
  202: { phase: "post-match", description: "Ended match on 2" },
  203: { phase: "post-match", description: "Ended match on 3" },
}

export enum EventCode {
  START_1 = 31,
  START_2 = 32,
  START_3 = 33,

  // Sandstorm
  SAND_CROSS_START = 0,
  SAND_HATCH_FLOOR = 20,
  SAND_HATCH_STATION = 21,
  SAND_CARGO_FLOOR = 40,
  SAND_CARGO_STATION = 41,
  SAND_HATCH_FRONT_BOT = 25,
  SAND_HATCH_FRONT_MID = 27,
  SAND_HATCH_FRONT_TOP = 29,
  SAND_HATCH_BACK_BOT = 24,
  SAND_HATCH_BACK_MID = 26,
  SAND_HATCH_BACK_TOP = 28,
  SAND_CARGO_BOT = 44,
  SAND_CARGO_MID = 45,
  SAND_CARGO_TOP = 46,
  SAND_HATCH_SHIP_SIDE = 23,
  SAND_HATCH_SHIP_FRONT = 22,
  SAND_CARGO_SHIP_SIDE = 43,
  SAND_CARGO_SHIP_FRONT = 42,
  SAND_DROP_HATCH = 2,
  SAND_DROP_CARGO = 3,
  SAND_ENTER_OT = 1,
  SAND_LEAVE_OT = 4,

  // Teleop
  GRAB_HATCH_FLOOR = 120,
  GRAB_HATCH_STATION = 121,
  GRAB_CARGO_FLOOR = 140,
  GRAB_CARGO_STATION = 141,
  HATCH_FRONT_BOT = 125,
  HATCH_FRONT_MID = 127,
  HATCH_FRONT_TOP = 129,
  HATCH_BACK_BOT = 124,
  HATCH_BACK_MID = 126,
  HATCH_BACK_TOP = 128,
  CARGO_BOT = 144,
  CARGO_MID = 145,
  CARGO_TOP = 146,
  HATCH_SHIP_SIDE = 123,
  HATCH_SHIP_FRONT = 122,
  CARGO_SHIP_SIDE = 143,
  CARGO_SHIP_FRONT = 142,
  DISABLED = 5,
  RESTORED = 6,
  DROP_HATCH = 12,
  DROP_CARGO = 13,
  ENTER_OT = 11,
  LEAVE_OT = 14,

  // Post-match
  LIFTED_2 = 212,
  LIFTED_3 = 213,
  ENDED_1 = 201,
  ENDED_2 = 202,
  ENDED_3 = 203,
}
